
#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Get environment variables from Replit Secrets
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ Missing Supabase credentials in Secrets. Please add:');
  console.error('   - SUPABASE_URL');
  console.error('   - SUPABASE_ANON_KEY');
  console.error('   - DATABASE_URL');
  process.exit(1);
}

// Create .env file content
const envContent = `# This file is automatically generated from your Replit Secrets
# Do not edit manually - it will be overwritten

# Client-side environment variables for Supabase
VITE_SUPABASE_URL=${supabaseUrl}
VITE_SUPABASE_ANON_KEY=${supabaseAnonKey}

# Generated on: ${new Date().toISOString()}
`;

// Write to .env file
fs.writeFileSync('.env', envContent);

console.log('✅ Environment variables successfully copied from Secrets to .env file');
console.log('🚀 You can now restart your application');
